### ISSUE TITLE
'Default' should use authent-ldap settings

### ISSUE THREAD

**Issue by Hipska** [knowitop/knowitop-multi-ldap-auth#1]
Would be nice to not need to include default settings again, but use the settings from authent-ldap module when a user has config set to 'default'.

**Comment by vbkunin** [comment]
Hi @Hipska!
Goog idea, I'll add it soon as well as the extending UserLDAP.

**Comment by vbkunin** [comment]
I've made many changes in the module (https://github.com/knowitop/knowitop-multi-ldap-auth/commit/f61ec51216840fd2de964fdce6cca21a64ac63ec). @Hipska, may I ask you for a little code review? Especially the part with rewriting authent-ldap config params:
https://github.com/knowitop/knowitop-multi-ldap-auth/blob/f61ec51216840fd2de964fdce6cca21a64ac63ec/model.knowitop-multi-ldap-auth.php#L85
Is it safe? And is there any other way not to copy/paste all code from UserLDAP::CheckCredentials?
Thanks!

**Comment by Hipska** [comment]
I think that might break stuff when on config edit page.

I was only suggesting that setting user config to 'Default', that your code uses the config from authent-ldap instead of that there is the need to specify a default config in your local module config again.

**Comment by vbkunin** [comment]
Thanks! I checked the config editor and it works fine.

I also added the ability to use the authent-ldap parameters as default for this module. But now you don't need to type 'default' or any other configuration name specified in the config, just select a value from the list.

**Comment by Hipska** [comment]
Still not what is requested in this issue. You still need to specify default configuration in config file while you already have it in authent-ldap section

**Comment by vbkunin** [comment]
No, you don't. Even you have an empty module config section `'knowitop-multi-ldap-auth' => array(),` you still have one option in user's account: _Use standard LDAP (localhost:389)_. But the module adds its ldap configuration during installation because the main purpose is to allow multiple ldap servers.
