### ISSUE TITLE
Is compatible with 3.0

### ISSUE THREAD

**Issue by lbllx** [knowitop/knowitop-multi-ldap-auth#2]
Hi,
I have this extension on iTop 271. I would like to upgrade iTop to 3.0.0 (the last version)
Is this extension working on iTop 3.0.0 ?
Thank you for your help

**Comment by vbkunin** [comment]
Hi!
I have not checked compatibility, it is more likely to work with the new version of iTop. Be sure to check on the test environment before updating the production.
